services:
  catalogdb:
    image: postgres
    user: root


  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    user: root

volumes:
  postgres_catalog:
